import base64
import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

import markdown


def _summary_to_html(summary_text):
    """Convert markdown summary to HTML for the email body."""
    html_body = markdown.markdown(summary_text, extensions=['nl2br'])
    return f"""<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
  body {{ font-family: Arial, sans-serif; max-width: 700px; margin: 0 auto; padding: 20px; color: #333; }}
  h2 {{ color: #2c5282; border-bottom: 2px solid #ebf4ff; padding-bottom: 8px; }}
  ul {{ padding-left: 20px; }}
  li {{ margin-bottom: 6px; }}
  .footer {{ margin-top: 40px; font-size: 12px; color: #999; border-top: 1px solid #eee; padding-top: 12px; }}
  .glance {{ background: #ebf8ff; border-left: 4px solid #3182ce; padding: 12px 16px; border-radius: 4px; }}
</style>
</head>
<body>
  {html_body}
  <div class="footer">
    This summary was automatically generated by School Email Digest.<br>
    Emails scanned: read-only access, no emails were modified or sent from your school inbox.
  </div>
</body>
</html>"""


def send_digest(summary_text, dest_email, school_email, gmail_service):
    """Send the weekly summary digest via Gmail API (avoids SMTP port restrictions)."""
    today = datetime.date.today()
    subject = f"📚 School Week Digest — {today.strftime('%B %d, %Y')}"

    msg = MIMEMultipart('alternative')
    msg['Subject'] = subject
    msg['From'] = f'School Digest <{school_email}>'
    msg['To'] = dest_email

    plain = MIMEText(summary_text, 'plain', 'utf-8')
    html = MIMEText(_summary_to_html(summary_text), 'html', 'utf-8')
    msg.attach(plain)
    msg.attach(html)

    raw = base64.urlsafe_b64encode(msg.as_bytes()).decode('utf-8')
    gmail_service.users().messages().send(
        userId='me',
        body={'raw': raw},
    ).execute()
